
FROM mcr.microsoft.com/dotnet/sdk:8.0

WORKDIR /src

RUN dotnet tool install --global dotnet-ef
ENV PATH="$PATH:/root/.dotnet/tools"

COPY ProjectManagerApi/ProjectManagerApi.csproj .

RUN dotnet restore

COPY ProjectManagerApi/ .

RUN dotnet publish -c Release -o /app

WORKDIR /app

ENTRYPOINT ["/bin/bash", "-c", "cd /src && dotnet ef database update && cd /app && dotnet ProjectManagerApi.dll"]